# Generated by Django 4.2.7 on 2023-11-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='desk',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='task',
            new_name='Task',
        ),
    ]
